name: Payment Jobs CD

on:
  push:
    branches:
      - main
    paths:
      - "jobs/payment-jobs/**"
      - "pay-api/src/pay_api/models/**"
      - "pay-api/src/pay_api/services/cfs_service.py"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - prod

jobs:
  pay-api-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cd-ocp.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "payment-jobs"
      working_directory: "./jobs/payment-jobs"
    secrets:
      OP_CONNECT_URL: ${{ secrets.OP_CONNECT_URL }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT4_DOCKER_REGISTRY }}
      OPENSHIFT_LOGIN_REGISTRY: ${{secrets.OPENSHIFT4_LOGIN_REGISTRY}}
      OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT4_SA_NAME }}
      OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT4_SA_TOKEN }}
      OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT4_REPOSITORY }}
